%% generated by soap from: /Users/bogdanrogalski/work/soap/test/soap_SUITE_data/tempconvert.wsdl
%% for service "TempConvert" and port "TempConvertSoap"
%% using options: [{service,"TempConvert"},{port,"TempConvertSoap"},{generate,client},{namespaces,[{"https://www.w3schools.com/xml/","P0"}]},{generate_tests,client},{http_client,soap_client_ibrowse},{client_name,"tempconvert_client"},{strict,true}]

-module(tempconvert_client).

-include("tempconvert.hrl").

-export([interface/0]).

%% The functions that are described by the WSDL
-export(['FahrenheitToCelsius'/3]).
-export(['CelsiusToFahrenheit'/3]).

-spec 'FahrenheitToCelsius'(Soap_body::'P0:FahrenheitToCelsius'(),
  Soap_headers::[soap:soap_header()],
  Options::[any()]) -> soap:soap_response('P0:FahrenheitToCelsiusResponse'()).
'FahrenheitToCelsius'(Soap_body, Soap_headers, Options) ->
  soap_client_util:call(Soap_body, Soap_headers, Options, "\"https://www.w3schools.com/xml/FahrenheitToCelsius\"", interface()).

-spec 'CelsiusToFahrenheit'(Soap_body::'P0:CelsiusToFahrenheit'(),
  Soap_headers::[soap:soap_header()],
  Options::[any()]) -> soap:soap_response('P0:CelsiusToFahrenheitResponse'()).
'CelsiusToFahrenheit'(Soap_body, Soap_headers, Options) ->
  soap_client_util:call(Soap_body, Soap_headers, Options, "\"https://www.w3schools.com/xml/CelsiusToFahrenheit\"", interface()).

%%% --------------------------------------------------------------------
%%% Internal functions
%%% --------------------------------------------------------------------
interface() ->
    ?INTERFACE.